name: Deployment Information
description: Retrieves information related to the deployment
runs-on: ubuntu-latest
timeout-minutes: 15
outputs:
  full_sha:
    value: ${{ steps.git_info.outputs.full_sha }}
  short_sha:
    value: ${{ steps.git_info.outputs.short_sha }}
  deployment_env:
    value: ${{ steps.deployment_info.outputs.env }}
  deployment_url:
    value: ${{ steps.deployment_info.outputs.url }}
  iam_role:
    value: ${{ steps.deployment_info.outputs.iam_role }}
  s3_bucket:
    value: ${{ steps.deployment_info.outputs.s3_bucket }}
env:
  PROD_BUCKET_NAME: production-deployment
  PROD_IAM_ROLE: arn:aws:iam::1:role/FakeProdServiceAccount
  QA_BUCKET_NAME: qa-deployment
  QA_IAM_ROLE: arn:aws:iam::1:role/FakeQAServiceAccount
  DEV_BUCKET_NAME: development-deployment
  DEV_IAM_ROLE: arn:aws:iam::1:role/FakeDevServiceAccount
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract Git Info
      id: git_info
      shell: bash
      run: |
        if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
          SHA=$GITHUB_SHA
        elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          SHA=${{ github.event.pull_request.head.sha }}
        fi
        echo "::set-output name=full_sha::$(git rev-parse "$SHA")"
        echo "::set-output name=short_sha::$(git rev-parse --short=7 "$SHA")"
    - name: Extract Deployment Info
      id: deployment_info
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/heads/develop' ]]; then
          echo "::set-output name=env::development"
          echo "::set-output name=url::https://dev.my.cadence.care"
          echo "::set-output name=iam_role::$DEV_IAM_ROLE"
          echo "::set-output name=s3_bucket::$DEV_BUCKET_NAME"
        elif [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/heads/main' ]]; then
          echo "::set-output name=env::production"
          echo "::set-output name=url::https://my.cadence.care"
          echo "::set-output name=iam_role::$PROD_IAM_ROLE"
          echo "::set-output name=s3_bucket::$PROD_BUCKET_NAME"
        elif [[ "${{ github.event_name }}" == 'push' && "${{ github.event.ref }}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
          echo "::set-output name=env::qa"
          echo "::set-output name=url::https://qa.my.cadence.care"
          echo "::set-output name=iam_role::$QA_IAM_ROLE"
          echo "::set-output name=s3_bucket::$QA_BUCKET_NAME"
        else
          echo "::set-output name=env::preview"
          echo "::set-output name=url::https://${{ steps.git_info.outputs.short_sha }}.preview.my.cadence.care"
          echo "::set-output name=iam_role::$QA_IAM_ROLE"
          echo "::set-output name=s3_bucket::$QA_BUCKET_NAME"
        fi
