name: CI+CD
on:
  push:
    branches:
      - main
      - develop
    tags:
      # Run when pushing release candidate tags
      - '[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'
  pull_request:
    branches:
      - main
      - develop
jobs:
  deployment_info:
    runs-on: ubuntu-latest
    outputs:
      deployment_env: ${{ steps.deployment_info.outputs.deployment_env }}
      deployment_url: ${{ steps.deployment_info.outputs.deployment_url }}
      iam_role: ${{ steps.deployment_info.outputs.iam_role }}
      s3_bucket: ${{ steps.deployment_info.outputs.s3_bucket }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract Deployment Info
        id: deployment_info
        uses: ./.github/actions/deployment_info
  build_for_preview:
    needs: deployment_info
    if: ${{ needs.deployment_info.outputs.deployment_env == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build For Environment
        uses: ./.github/actions/build
        env:
          REACT_APP_WELCOME_MESSAGE: ${{ secrets.REACT_APP_WELCOME_MESSAGE }}
  build_for_env:
    needs: deployment_info
    if: ${{ needs.deployment_info.outputs.deployment_env == 'development' || needs.deployment_info.outputs.deployment_env == 'qa' || needs.deployment_info.outputs.deployment_env == 'production' }}
    environment:
      name: ${{ needs.deployment_info.outputs.deployment_env }}
      url: ${{ needs.deployment_info.outputs.deployment_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build For Environment
        uses: ./.github/actions/build
        env:
          REACT_APP_WELCOME_MESSAGE: ${{ secrets.REACT_APP_WELCOME_MESSAGE }}
  deploy:
    needs:
      - deployment_info
      - build_for_env
    if: ${{ needs.deployment_info.outputs.deployment_env == 'development' || needs.deployment_info.outputs.deployment_env == 'qa' || needs.deployment_info.outputs.deployment_env == 'production' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.deployment_info.outputs.deployment_env }}
      url: ${{ needs.deployment_info.outputs.deployment_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          bucket-name: ${{ needs.deployment_info.outputs.s3_bucket }}
          iam-role: ${{ needs.deployment_info.outputs.iam_role }}
          # TODO: Need to create a new one for github?
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
  deploy_preview:
    needs:
      - deployment_info
      - build_for_preview
    if: ${{ needs.deployment_info.outputs.deployment_env == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          bucket-name: ${{ needs.deployment_info.outputs.s3_bucket }}
          iam-role: ${{ needs.deployment_info.outputs.iam_role }}
          # TODO: Need to create a new one for github?
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          is-preview: true
